### ISSUE TITLE
KeyError: 'transform'

### ISSUE THREAD

**Issue by lzq0115** [lgsvl/simulator#1302]
Hello, lgsvl team.
I am using PythonAPI and gym-lgsvl to control lgsvl and I am using it to perform a reinforcement learning which needs to interact with the environment frequently.(I guess this would be the problem?) I read issue #990, he got this error because of not using sim.run(). But I use sim.run(time_limit=1/20, time_scale=10) function.  Mostly the code works well and is able to finish the whole job. But when this error appears, all I can do is stop it and start it over, which is frustrating. I get this error randomly and I cannot reproduce this error. I can get this error both on Windows 10 and Ubuntu 16.04 with lgsvl 2020.06 version. 

Here is a picture of the variable that cause the error and error info is as follows.
![image](https://user-images.githubusercontent.com/80949182/112116570-61439700-8bf5-11eb-9366-24372f03c2bb.png)

Traceback (most recent call last):
  File "/home/trevor/Downloads/pycharm-2020.1/plugins/python/helpers/pydev/pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/trevor/Downloads/pycharm-2020.1/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/trevor/lgsvl_RL/main.py", line 78, in <module>
    s_prime, reward, done, info = env.step(v_action)
  File "/home/trevor/anaconda3/envs/lgsvl/lib/python3.7/site-packages/gym/wrappers/time_limit.py", line 16, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/trevor/lgsvl/gym-lgsvl-master/gym_lgsvl/envs/lgsvl_env_new.py", line 123, in step
    print("real speed is " + str(self.ego.state.speed))
  File "/home/trevor/lgsvl/PythonAPI-master/lgsvl/agent.py", line 114, in state
    return AgentState.from_json(j)
  File "/home/trevor/lgsvl/PythonAPI-master/lgsvl/utils.py", line 60, in from_json
    Transform.from_json(j["transform"]),
KeyError: 'transform'

**Comment by EricBoiseLGSVL** [comment]
Are you in interactive mode?

**Comment by lzq0115** [comment]
> Are you in interactive mode?

Nope, interactive mode is not chosen.

**Comment by EricBoiseLGSVL** [comment]
Sorry we will need more info to debug this.  Can you post the api script you are running or a simplified one that we can see the error?  @hadiTab any idea?

**Comment by lzq0115** [comment]
I think only the whole project would find the problem, so I post it on my github. https://github.com/lzq0115/lgsvl_RL.git
Please have a look. The code may be poorly written. Hope this will not be a trouble for you.

**Comment by EricBoiseLGSVL** [comment]
No we cannot troubleshoot the entire project.  Please post the api script you are running here and we can see if we can reproduce the issue.

**Comment by lzq0115** [comment]
Sorry for the late reply. Here is the api script.
```python
import gym
from gym import error, spaces, utils
from gym.utils import seeding
import numpy as np
import lgsvl
from lgsvl.geometry import Vector, Transform
import os
import random
import math
import cv2

CONFIG = {
    "scene": "WideFlatMap",
    "port": 8181,

    "action_space":
        spaces.Box(
            np.array([-1], dtype=np.float32),
            np.array([+1], dtype=np.float32)
        ),  # throttle (+) / brake (-)

    "observation_space":
        spaces.Box(
            low=np.array([-10, -25], dtype=np.float32),
            high=np.array([50, 25], dtype=np.float32)
        )  # delta_dis & delta_v
}
step_size = 1/20
initial_speed = 10
max_step = 900


class LgsvlEnvNew(gym.Env):
    metadata = {'render.modes': ['human']}

    def __init__(self, config=CONFIG):

        self.env = lgsvl.Simulator(os.environ.get("SIMULATOR_HOST", "127.0.0.1"), config["port"])
        if self.env.current_scene == config["scene"]:
            self.env.reset()
        else:
            self.env.load(config["scene"])

        self.spawns = self.env.get_spawn()
        self.vehicles = dict()
        self._occupied = list()
        self.ego = None
        self.npc = None
        self.seed()
        self.control = lgsvl.VehicleControl()
        self.forward = None
        self.origin = None

        self.action_space = config["action_space"]
        self.observation_space = config["observation_space"]
        self.v = 0
        self.v_old = 0
        self.delta_dis = 0
        self.delta_v = 0
        self.accel = 0
        self.desired_speed = 10
        self.prev_cte = 0.0
        self.int_cte = 0.0

        self.count = 0

        self.reward = 0
        self.done = False

    def seed(self, seed=0):
        np.random.seed(seed)

    def reset(self):
        """
    Resets environment for a new episode.
    """
        print('Simulation reset!!')
        self.count = 0
        self.done = False
        self.vehicles.clear()
        self._occupied.clear()
        self.spawns.clear()
        self.env.reset()
        self.spawns = self.env.get_spawn()
        self._setup_ego()
        self._setup_npc()
        self.prev_cte = self.ego.state.speed - self.desired_speed
        self.int_cte = 0.0
        self.count += 1

        return self._get_observation(1)

    def step(self, action):
        """
    Run one step of the simulation.
    """
        print('Step!!')
        print('speed demand is ' + str(action) + ' m/s')
        # control npc trajectory
        self.set_npc_waypoints()
        self.set_ego_direction()
        
        self.reward = 0

        output = self.pid(8.5, 0, 0, action)
        if output > 0:
            self.control.throttle = output
            self.control.braking = 0.0
            print('throttle is ' + str(output))
        else:
            self.control.throttle = 0.0
            self.control.braking = abs(output)
            print('braking is ' + str(abs(output)))

        self.ego.apply_control(self.control, sticky=True)
        self.ego.on_collision(self._on_collision)
        self.env.run(time_limit=step_size, time_scale=10)

        print("real speed is " + str(self.ego.state.speed))
        observation = self._get_observation()
        self.too_far_and_too_long(observation)

        self._calculate_reward(observation)
        self.count += 1
        info = {}
        print('reward is ' + str(self.reward))
        return observation, self.reward, self.done, info

    def pid(self, tau_p, tau_i, tau_d, set_speed):
        cte = self.ego.state.speed - set_speed
        diff_cte = cte - self.prev_cte
        # prev_prev_cte = self.prev_cte
        self.prev_cte = cte
        self.int_cte += cte
        pid_raw = -tau_p * cte - tau_i * self.int_cte - tau_d * diff_cte
        if pid_raw > 100:
            output = 100
        elif pid_raw < -100:
            output = -100
        else:
            output = pid_raw

        return output

    def _on_collision(self, agent1, agent2, contact):
        """
    Collision callback -- results in a negative reward.
    """
        self.reward -= 3000000
        self.too_short_punish()
        self.done = True
        name1 = self.vehicles[agent1]
        name2 = self.vehicles[agent2] if agent2 is not None else "OBSTACLE"
        print("{} collided with {} at {}".format(name1, name2, contact))
        
    def too_far_and_too_long(self, observation):
        if observation[0] > 50:
            self.reward -= 2000000
            self.too_short_punish()
            self.done = True
            print('too far!!')
        if self.count > max_step:
            self.done = True

    def _calculate_reward(self, observation, Q1=8, Q2=2, R=0.1):
        """
    Reward is calculated.
    """
        self.reward -= self.delta_dis*Q1*self.delta_dis + self.delta_v*Q2*self.delta_v + self.accel*R*self.accel
        if observation[0] < 0 or observation[0] > 0.1:  # change to 0
            self.reward -= 500
            if abs(observation[0]) > 0.5:
                self.reward -= 500
                if abs(observation[0]) > 5:
                    self.reward -= 1000
                    if abs(observation[0]) > 10:
                        self.reward -= 200 * abs(observation[0])

    def _distance_travelled(self):
        """
    Helper function to calculate the distance travelled by the ego
    vehicle. Makes an API call for position at each step.
    """
        last_pos = self.ego_position
        self.ego_position = self.ego.transform.position
        return self._proximity(last_pos, self.ego_position)

    def render(self, mode='human'):
        pass

    def close(self):
        self.env.stop()

    def _setup_ego(self, name="Lexus2016RXHybrid (Autoware)", spawn_index=0, random_spawn=False):
        """
    Spawns ego vehicle at the specified (by default index 0) spawn point in the Unity scene.
    """
        state = lgsvl.AgentState()
        if random_spawn:
            state.transform = self.spawns[random.randint(0, len(self.spawns) - 1)]
        else:
            state.transform = self.spawns[spawn_index]
            state.transform.rotation = lgsvl.Vector(0, 0, 0)
            self.forward = lgsvl.utils.transform_to_forward(state.transform)
            state.velocity = initial_speed * self.forward  # set to 10

        self.ego = self.env.add_agent(name, lgsvl.AgentType.EGO, state)
        self.vehicles[self.ego] = "EGO"
        self._occupied.append(state.transform.position)
        self.sensors = self.ego.get_sensors()
        for s in self.sensors:
            if s.name == "Main Camera":
                self.camera = s
                break
        self.ego_position = self.ego.state.transform.position
        self.origin = [self.ego.state.transform.position, self.ego.state.transform.rotation]
        self.ego_transform = self.ego.state.transform

    def _setup_npc(self, follow_lane=False, speed=None, speed_upper=25.0, speed_lower=0.0):
        npc_type = "SUV"

        state = lgsvl.AgentState()
        # self.forward = lgsvl.utils.transform_to_forward(self.ego_transform)
        state.velocity = initial_speed * self.forward  # set to 10
        state.transform.position = self.ego_position + 10 * self.forward  # 10m forwards
        state.transform.rotation = self.ego.transform.rotation
        self.npc = self.env.add_agent(npc_type, lgsvl.AgentType.NPC, state)

        if follow_lane:
            if not speed:
                speed = random.uniform(speed_lower, speed_upper)  # change to variable speed
            self.npc.follow_closest_lane(True, speed)

        self.vehicles[self.npc] = npc_type
        self._occupied.append(state.transform.position)

    def _proximity(self, position1, position2):
        """
    Helper function for calculating Euclidean distance between two Vector objects.
    """
        return math.sqrt(
            (position1.x - position2.x) ** 2 + (position1.y - position2.y) ** 2 + (position1.z - position2.z) ** 2)

    def _get_observation(self, is_reset=0):
        tao = 3
        d0 = 10
        ego_position = self.ego.state.position
        npc_position = self.npc.state.position
        ego_speed = self.ego.state.speed
        if is_reset:
            self.v_old = 0
            self.v = ego_speed
        else:
            self.v_old = self.v
            self.v = ego_speed
            self.accel = (self.v - self.v_old) / step_size
        npc_speed = self.npc.state.speed
        dis = self._proximity(ego_position, npc_position)
        if npc_position.z - ego_position.z < 0:
            dis = -dis
        target_dis = ego_speed * tao + d0
        self.delta_dis = dis - target_dis
        self.delta_v = npc_speed - ego_speed
        print("dis is " + str(dis))

        return [self.delta_dis, self.delta_v]

    def get_origin(self):
        return self.origin, self.forward

    def set_npc_waypoints(self):
        waypoints = []
        self.update_origin()
        point = [self.origin[0] + 20 * self.forward, self.origin[0] + 27.13 * self.forward,
                 self.origin[0] + 34.95 * self.forward, self.origin[0] + 43.44 * self.forward,
                 self.origin[0] + 52.62 * self.forward, self.origin[0] + 62.47 * self.forward,
                 self.origin[0] + 73 * self.forward, self.origin[0] + 84.22 * self.forward,
                 self.origin[0] + 96.11 * self.forward, self.origin[0] + 108.62 * self.forward,
                 self.origin[0] + 121.93 * self.forward, self.origin[0] + 135.87 * self.forward,
                 self.origin[0] + 150.48 * self.forward, self.origin[0] + 165.77 * self.forward,
                 self.origin[0] + 181.74 * self.forward, self.origin[0] + 198.39 * self.forward,
                 self.origin[0] + 398.39 * self.forward, self.origin[0] + 403.38 * self.forward,
                 self.origin[0] + 408.18 * self.forward, self.origin[0] + 412.76 * self.forward,
                 self.origin[0] + 417.15 * self.forward, self.origin[0] + 421.32 * self.forward,
                 self.origin[0] + 425.30 * self.forward, self.origin[0] + 429.07 * self.forward,
                 self.origin[0] + 432.64 * self.forward, self.origin[0] + 436.01 * self.forward,
                 self.origin[0] + 439.17 * self.forward, self.origin[0] + 442.12 * self.forward,
                 self.origin[0] + 444.88 * self.forward, self.origin[0] + 447.42 * self.forward,
                 self.origin[0] + 449.77 * self.forward, self.origin[0] + 451.91 * self.forward,
                 self.origin[0] + 453.85 * self.forward, self.origin[0] + 455.58 * self.forward,
                 self.origin[0] + 457.11 * self.forward, self.origin[0] + 458.43 * self.forward,
                 self.origin[0] + 459.55 * self.forward, self.origin[0] + 460.47 * self.forward,
                 self.origin[0] + 461.18 * self.forward, self.origin[0] + 461.69 * self.forward,
                 self.origin[0] + 462 * self.forward, self.origin[0] + 462.1 * self.forward]
        wp = [lgsvl.DriveWaypoint(point[0], 10, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[1], 11, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[2], 12, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[3], 13, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[4], 14, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[5], 15, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[6], 16, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[7], 17, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[8], 18, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[9], 19, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[10], 20, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[11], 21, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[12], 22, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[13], 23, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[14], 24, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[15], 25, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[16], 25, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[17], 24, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[18], 23, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[19], 22, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[20], 21, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[21], 20, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[22], 19, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[23], 18, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[24], 17, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[25], 16, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[26], 15, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[27], 14, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[28], 13, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[29], 12, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[30], 11, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[31], 10, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[32], 9, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[33], 8, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[34], 7, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[35], 6, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[36], 5, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[37], 4, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[38], 3, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[39], 2, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[40], 1, self.ego.transform.rotation),
              lgsvl.DriveWaypoint(point[41], 0, self.ego.transform.rotation)]
        for i in range(42):  # set to 42
            if self.npc.state.position.z < point[i].z:
                waypoints.append(wp[i])
        if waypoints:
            self.npc.follow(waypoints)

    def set_ego_direction(self):
        s = self.ego.state
        s.transform.rotation = self.forward
        self.ego.state = s

    def update_origin(self):  # no need, but better than no
        self.origin[0].y = self.ego.state.transform.position.y

    def too_short_punish(self):
        if self.count < max_step:
            self.reward -= 20000 * (max_step - self.count)
```

**Comment by EricBoiseLGSVL** [comment]
Thanks for the file.  I'll need to ask @daviduhm and @hadiTab on the open ai gym integration.  It seems odd that it fails to return the transform.  Have you tried the latest simulator and python api?

**Comment by lzq0115** [comment]
Not yet, I don't even know the new version was released. I will try it.

**Comment by lzq0115** [comment]
OK, I try with the new version 2021.1 and new python API. The problem will appear even much more earlier than the old version 2020.6.
