### ISSUE TITLE
Error when running pythonAPI

### ISSUE THREAD

**Issue by Czl0223** [lgsvl/simulator#1307]
When I tested according to the description of pythonAPI in the given document of LGSVL, an error occurred, https://www.svlsimulator.com/docs/python-api/python-api/.
My operating system is windows10, all the steps are as follows:
1. Install python3.7
2. From the URL https://github.com/lgsvl/PythonAPI, git pythonAPI
3. Run the cmd command, enter the pythonAPI folder, and run the command pip3 install --user -e.
4. Run the Simulator executable file, select pythonAPI mode, and prompt API ready!
So far, there are no problems.
But when I execute the command ./quickstart/05-ego-drive-in-circle.py, an error occurred, as follows:

Python API Quickstart #5: Ego vehicle driving in circle
Traceback (most recent call last):
  File "D:\PythonAPI\quickstart\05-ego-drive-in-circle.py", line 19, in <module>
    sim.load(lgsvl.wise.DefaultAssets.map_borregasave)
  File "d:\pythonapi\lgsvl\utils.py", line 23, in new_f
    return f(*args, **kwargs)
  File "d:\pythonapi\lgsvl\simulator.py", line 43, in load
    self.remote.command("simulator/load_scene", {"scene": scene, "seed": seed})
  File "d:\pythonapi\lgsvl\remote.py", line 69, in command
    raise Exception(data["error"])
Exception: Could not find asset with Id aae03d2a-b7ca-4a88-9e41-9035287a12cc (Unauthorized)

Among them, "aae03d2a-b7ca-4a88-9e41-9035287a12cc" seems to be the UUID of the borregasave map. This error seems to be that the corresponding map is not found? How to solve this?

**Comment by lemketron** [comment]
Are you using SVL Simulator (2021.1) or LGSVL Simulator (2020.06 or older)?

If you're using LGSVL 2020.06, you will probably want to `git checkout preview` 

If you're using SVL 2021.1, then this is the map that script is attempting to load :
https://wise.svlsimulator.com/maps/profile/aae03d2a-b7ca-4a88-9e41-9035287a12cc

Loading maps by UUID doesn't work with 2020.06 but if you checkout the "preview" tag of PythonAPI you should have better luck.
