### ISSUE TITLE
Unable to Launch the simulator on ubuntu

### ISSUE THREAD

**Issue by rajeshjoshi8792** [lgsvl/simulator#1594]
Hi,

i m executing simulator in ubuntu. but its not opening. 

i m using Tightvnc to connect my server.

here is my player.log file.
Mono path[0] = '/home/ubuntu/Rajesh/svlsimulator-linux64-2021.2/simulator_Data/Managed'
Mono config path = '/home/ubuntu/Rajesh/svlsimulator-linux64-2021.2/simulator_Data/MonoBleedingEdge/etc'
Preloaded 'UnityFbxSdkNative.so'
Preloaded 'liblaszip.so'
Preloaded 'libpng.so'
Preloaded 'libsqlite3.so'
Preloaded 'libturbojpeg.so'
Display 0 '0': 1024x768 (primary device).
Loading player data from /home/ubuntu/Rajesh/svlsimulator-linux64-2021.2/simulator_Data/data.unity3d
Unable to load player prefs
Desktop is 1024 x 768 @ 0 Hz
Xlib:  extension "GLX" missing on display ":1".
Xlib:  extension "GLX" missing on display ":1".
Xlib:  extension "GLX" missing on display ":1".
Xlib:  extension "GLX" missing on display ":1".
Xlib:  extension "GLX" missing on display ":1".
Xlib:  extension "GLX" missing on display ":1".
Xlib:  extension "GLX" missing on display ":1".
Xlib:  extension "GLX" missing on display ":1".
[Vulkan init] extensions: count=2
[Vulkan init] extensions: name=VK_EXT_debug_report, enabled=0
[Vulkan init] extensions: name=VK_EXT_debug_utils, enabled=0
Xlib:  extension "GLX" missing on display ":1".
Xlib:  extension "GLX" missing on display ":1".
Xlib:  extension "GLX" missing on display ":1".
Xlib:  extension "GLX" missing on display ":1".
Vulkan detection: 0
No supported renderers found, exiting

please help me resolve this issue.

**Comment by lemketron** [comment]
Please refer to #1431 and #1503 (or [search issues for "VNC"](https://github.com/lgsvl/simulator/issues?q=is%3Aissue+vnc+))

**Comment by rajeshjoshi8792** [comment]
i refer all the topics related to simulator not opening. and tried all the steps. but still simulator not opening.

but this times, the error is different. please check my player.log file


Mono path[0] = '/home/ubuntu/Rajesh/SVL Simulator/svlsimulator-linux64-2021.2/simulator_Data/Managed'
Mono config path = '/home/ubuntu/Rajesh/SVL Simulator/svlsimulator-linux64-2021.2/simulator_Data/MonoBleedingEdge/etc'
Preloaded 'UnityFbxSdkNative.so'
Preloaded 'liblaszip.so'
Preloaded 'libpng.so'
Preloaded 'libsqlite3.so'
Preloaded 'libturbojpeg.so'
Display 0 '0': 1024x768 (primary device).
Loading player data from /home/ubuntu/Rajesh/SVL Simulator/svlsimulator-linux64-2021.2/simulator_Data/data.unity3d
Desktop is 1024 x 768 @ 0 Hz
Xlib:  extension "GLX" missing on display ":1.0".
Xlib:  extension "GLX" missing on display ":1.0".
[Vulkan init] extensions: count=17
[Vulkan init] extensions: name=VK_KHR_device_group_creation, enabled=0
[Vulkan init] extensions: name=VK_KHR_display, enabled=1
[Vulkan init] extensions: name=VK_KHR_external_fence_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_memory_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_semaphore_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_get_display_properties2, enabled=0
[Vulkan init] extensions: name=VK_KHR_get_physical_device_properties2, enabled=1
[Vulkan init] extensions: name=VK_KHR_get_surface_capabilities2, enabled=0
[Vulkan init] extensions: name=VK_KHR_surface, enabled=1
[Vulkan init] extensions: name=VK_KHR_surface_protected_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_xcb_surface, enabled=0
[Vulkan init] extensions: name=VK_KHR_xlib_surface, enabled=1
[Vulkan init] extensions: name=VK_EXT_acquire_xlib_display, enabled=0
[Vulkan init] extensions: name=VK_EXT_debug_report, enabled=0
[Vulkan init] extensions: name=VK_EXT_debug_utils, enabled=0
[Vulkan init] extensions: name=VK_EXT_direct_mode_display, enabled=0
[Vulkan init] extensions: name=VK_EXT_display_surface_counter, enabled=0
Vulkan detection: 2
Initialize engine version: 2020.3.3f1 (76626098c1c4)
[Subsystems] Discovering subsystems at path /home/ubuntu/Rajesh/SVL Simulator/svlsimulator-linux64-2021.2/simulator_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Xlib:  extension "GLX" missing on display ":1.0".
Xlib:  extension "GLX" missing on display ":1.0".
[Vulkan init] extensions: count=17
[Vulkan init] extensions: name=VK_KHR_device_group_creation, enabled=0
[Vulkan init] extensions: name=VK_KHR_display, enabled=1
[Vulkan init] extensions: name=VK_KHR_external_fence_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_memory_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_semaphore_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_get_display_properties2, enabled=0
[Vulkan init] extensions: name=VK_KHR_get_physical_device_properties2, enabled=1
[Vulkan init] extensions: name=VK_KHR_get_surface_capabilities2, enabled=0
[Vulkan init] extensions: name=VK_KHR_surface, enabled=1
[Vulkan init] extensions: name=VK_KHR_surface_protected_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_xcb_surface, enabled=0
[Vulkan init] extensions: name=VK_KHR_xlib_surface, enabled=1
[Vulkan init] extensions: name=VK_EXT_acquire_xlib_display, enabled=0
[Vulkan init] extensions: name=VK_EXT_debug_report, enabled=0
[Vulkan init] extensions: name=VK_EXT_debug_utils, enabled=0
[Vulkan init] extensions: name=VK_EXT_direct_mode_display, enabled=0
[Vulkan init] extensions: name=VK_EXT_display_surface_counter, enabled=0
[Vulkan init] SelectPhysicalDevice requestedDeviceIndex=-1 xrDevice=(nil)
[Vulkan init] Physical Device 0x8c9f90 [0]: "Tesla T4" deviceType=2 vendorID=10de deviceID=1eb8
[Vulkan init] Selected physical device 0x8c9f90
[Vulkan init] Graphics queue count=1
[Vulkan init] extensions: count=128
[Vulkan init] extensions: name=VK_KHR_16bit_storage, enabled=0
[Vulkan init] extensions: name=VK_KHR_8bit_storage, enabled=0
[Vulkan init] extensions: name=VK_KHR_bind_memory2, enabled=0
[Vulkan init] extensions: name=VK_KHR_buffer_device_address, enabled=0
[Vulkan init] extensions: name=VK_KHR_copy_commands2, enabled=0
[Vulkan init] extensions: name=VK_KHR_create_renderpass2, enabled=1
[Vulkan init] extensions: name=VK_KHR_dedicated_allocation, enabled=1
[Vulkan init] extensions: name=VK_KHR_deferred_host_operations, enabled=0
[Vulkan init] extensions: name=VK_KHR_depth_stencil_resolve, enabled=1
[Vulkan init] extensions: name=VK_KHR_descriptor_update_template, enabled=1
[Vulkan init] extensions: name=VK_KHR_device_group, enabled=0
[Vulkan init] extensions: name=VK_KHR_draw_indirect_count, enabled=0
[Vulkan init] extensions: name=VK_KHR_driver_properties, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_fence, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_fence_fd, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_memory, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_memory_fd, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_semaphore, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_semaphore_fd, enabled=0
[Vulkan init] extensions: name=VK_KHR_fragment_shading_rate, enabled=0
[Vulkan init] extensions: name=VK_KHR_get_memory_requirements2, enabled=1
[Vulkan init] extensions: name=VK_KHR_image_format_list, enabled=1
[Vulkan init] extensions: name=VK_KHR_imageless_framebuffer, enabled=0
[Vulkan init] extensions: name=VK_KHR_maintenance1, enabled=1
[Vulkan init] extensions: name=VK_KHR_maintenance2, enabled=1
[Vulkan init] extensions: name=VK_KHR_maintenance3, enabled=0
[Vulkan init] extensions: name=VK_KHR_multiview, enabled=1
[Vulkan init] extensions: name=VK_KHR_pipeline_executable_properties, enabled=0
[Vulkan init] extensions: name=VK_KHR_pipeline_library, enabled=0
[Vulkan init] extensions: name=VK_KHR_push_descriptor, enabled=0
[Vulkan init] extensions: name=VK_KHR_relaxed_block_layout, enabled=0
[Vulkan init] extensions: name=VK_KHR_sampler_mirror_clamp_to_edge, enabled=1
[Vulkan init] extensions: name=VK_KHR_sampler_ycbcr_conversion, enabled=0
[Vulkan init] extensions: name=VK_KHR_separate_depth_stencil_layouts, enabled=0
[Vulkan init] extensions: name=VK_KHR_shader_atomic_int64, enabled=0
[Vulkan init] extensions: name=VK_KHR_shader_clock, enabled=0
[Vulkan init] extensions: name=VK_KHR_shader_draw_parameters, enabled=0
[Vulkan init] extensions: name=VK_KHR_shader_float16_int8, enabled=0
[Vulkan init] extensions: name=VK_KHR_shader_float_controls, enabled=0
[Vulkan init] extensions: name=VK_KHR_shader_non_semantic_info, enabled=0
[Vulkan init] extensions: name=VK_KHR_shader_subgroup_extended_types, enabled=0
[Vulkan init] extensions: name=VK_KHR_shader_terminate_invocation, enabled=0
[Vulkan init] extensions: name=VK_KHR_spirv_1_4, enabled=0
[Vulkan init] extensions: name=VK_KHR_storage_buffer_storage_class, enabled=0
[Vulkan init] extensions: name=VK_KHR_swapchain, enabled=1
[Vulkan init] extensions: name=VK_KHR_swapchain_mutable_format, enabled=0
[Vulkan init] extensions: name=VK_KHR_timeline_semaphore, enabled=0
[Vulkan init] extensions: name=VK_KHR_uniform_buffer_standard_layout, enabled=0
[Vulkan init] extensions: name=VK_KHR_variable_pointers, enabled=0
[Vulkan init] extensions: name=VK_KHR_vulkan_memory_model, enabled=0
[Vulkan init] extensions: name=VK_EXT_4444_formats, enabled=0
[Vulkan init] extensions: name=VK_EXT_blend_operation_advanced, enabled=0
[Vulkan init] extensions: name=VK_EXT_buffer_device_address, enabled=0
[Vulkan init] extensions: name=VK_EXT_calibrated_timestamps, enabled=0
[Vulkan init] extensions: name=VK_EXT_conditional_rendering, enabled=0
[Vulkan init] extensions: name=VK_EXT_conservative_rasterization, enabled=1
[Vulkan init] extensions: name=VK_EXT_custom_border_color, enabled=0
[Vulkan init] extensions: name=VK_EXT_depth_clip_enable, enabled=0
[Vulkan init] extensions: name=VK_EXT_depth_range_unrestricted, enabled=0
[Vulkan init] extensions: name=VK_EXT_descriptor_indexing, enabled=0
[Vulkan init] extensions: name=VK_EXT_discard_rectangles, enabled=0
[Vulkan init] extensions: name=VK_EXT_display_control, enabled=0
[Vulkan init] extensions: name=VK_EXT_extended_dynamic_state, enabled=0
[Vulkan init] extensions: name=VK_EXT_external_memory_host, enabled=0
[Vulkan init] extensions: name=VK_EXT_fragment_shader_interlock, enabled=0
[Vulkan init] extensions: name=VK_EXT_global_priority, enabled=0
[Vulkan init] extensions: name=VK_EXT_host_query_reset, enabled=0
[Vulkan init] extensions: name=VK_EXT_image_robustness, enabled=0
[Vulkan init] extensions: name=VK_EXT_index_type_uint8, enabled=0
[Vulkan init] extensions: name=VK_EXT_inline_uniform_block, enabled=0
[Vulkan init] extensions: name=VK_EXT_line_rasterization, enabled=0
[Vulkan init] extensions: name=VK_EXT_memory_budget, enabled=0
[Vulkan init] extensions: name=VK_EXT_pci_bus_info, enabled=0
[Vulkan init] extensions: name=VK_EXT_pipeline_creation_cache_control, enabled=0
[Vulkan init] extensions: name=VK_EXT_pipeline_creation_feedback, enabled=0
[Vulkan init] extensions: name=VK_EXT_post_depth_coverage, enabled=0
[Vulkan init] extensions: name=VK_EXT_private_data, enabled=0
[Vulkan init] extensions: name=VK_EXT_robustness2, enabled=0
[Vulkan init] extensions: name=VK_EXT_sample_locations, enabled=0
[Vulkan init] extensions: name=VK_EXT_sampler_filter_minmax, enabled=0
[Vulkan init] extensions: name=VK_EXT_scalar_block_layout, enabled=0
[Vulkan init] extensions: name=VK_EXT_separate_stencil_usage, enabled=0
[Vulkan init] extensions: name=VK_EXT_shader_atomic_float, enabled=0
[Vulkan init] extensions: name=VK_EXT_shader_demote_to_helper_invocation, enabled=0
[Vulkan init] extensions: name=VK_EXT_shader_image_atomic_int64, enabled=0
[Vulkan init] extensions: name=VK_EXT_shader_subgroup_ballot, enabled=0
[Vulkan init] extensions: name=VK_EXT_shader_subgroup_vote, enabled=0
[Vulkan init] extensions: name=VK_EXT_shader_viewport_index_layer, enabled=1
[Vulkan init] extensions: name=VK_EXT_subgroup_size_control, enabled=0
[Vulkan init] extensions: name=VK_EXT_texel_buffer_alignment, enabled=0
[Vulkan init] extensions: name=VK_EXT_tooling_info, enabled=0
[Vulkan init] extensions: name=VK_EXT_transform_feedback, enabled=0
[Vulkan init] extensions: name=VK_EXT_vertex_attribute_divisor, enabled=0
[Vulkan init] extensions: name=VK_EXT_ycbcr_image_arrays, enabled=0
[Vulkan init] extensions: name=VK_NV_clip_space_w_scaling, enabled=0
[Vulkan init] extensions: name=VK_NV_compute_shader_derivatives, enabled=0
[Vulkan init] extensions: name=VK_NV_cooperative_matrix, enabled=0
[Vulkan init] extensions: name=VK_NV_corner_sampled_image, enabled=0
[Vulkan init] extensions: name=VK_NV_coverage_reduction_mode, enabled=0
[Vulkan init] extensions: name=VK_NV_cuda_kernel_launch, enabled=0
[Vulkan init] extensions: name=VK_NV_dedicated_allocation, enabled=0
[Vulkan init] extensions: name=VK_NV_dedicated_allocation_image_aliasing, enabled=0
[Vulkan init] extensions: name=VK_NV_device_diagnostic_checkpoints, enabled=0
[Vulkan init] extensions: name=VK_NV_device_diagnostics_config, enabled=0
[Vulkan init] extensions: name=VK_NV_device_generated_commands, enabled=0
[Vulkan init] extensions: name=VK_NV_fill_rectangle, enabled=0
[Vulkan init] extensions: name=VK_NV_fragment_coverage_to_color, enabled=0
[Vulkan init] extensions: name=VK_NV_fragment_shader_barycentric, enabled=0
[Vulkan init] extensions: name=VK_NV_fragment_shading_rate_enums, enabled=0
[Vulkan init] extensions: name=VK_NV_framebuffer_mixed_samples, enabled=0
[Vulkan init] extensions: name=VK_NV_geometry_shader_passthrough, enabled=0
[Vulkan init] extensions: name=VK_NV_mesh_shader, enabled=0
[Vulkan init] extensions: name=VK_NV_ray_tracing, enabled=0
[Vulkan init] extensions: name=VK_NV_representative_fragment_test, enabled=0
[Vulkan init] extensions: name=VK_NV_sample_mask_override_coverage, enabled=0
[Vulkan init] extensions: name=VK_NV_scissor_exclusive, enabled=0
[Vulkan init] extensions: name=VK_NV_shader_image_footprint, enabled=0
[Vulkan init] extensions: name=VK_NV_shader_sm_builtins, enabled=0
[Vulkan init] extensions: name=VK_NV_shader_subgroup_partitioned, enabled=0
[Vulkan init] extensions: name=VK_NV_shading_rate_image, enabled=0
[Vulkan init] extensions: name=VK_NV_viewport_array2, enabled=0
[Vulkan init] extensions: name=VK_NV_viewport_swizzle, enabled=0
[Vulkan init] extensions: name=VK_NVX_binary_import, enabled=0
[Vulkan init] extensions: name=VK_NVX_image_view_handle, enabled=0
[Vulkan init] extensions: name=VK_NVX_multiview_per_view_attributes, enabled=0
[Vulkan init] extensions: name=VK_KHR_acceleration_structure, enabled=0
[Vulkan init] extensions: name=VK_KHR_ray_query, enabled=0
[Vulkan init] extensions: name=VK_KHR_ray_tracing_pipeline, enabled=0
Vulkan API version 1.1.0 (1.2.155 supported by driver, 1.1.0 requested)
Vulkan vendor=[NVIDIA] id=[10de]
Vulkan renderer=[Tesla T4] id=[1eb8]
Vulkan device type 2
Vulkan driverversion=[0x73150000] uint=[1930756096]
Vulkan PSO: cache data not found [path=/tmp/LGElectronics/SVLSimulator/vulkan_pso_cache.bin]
Begin MonoManager ReloadAssembly
- Completed reload, in  0.061 seconds
requesting resize 1024 x 768
resizing window to 1024 x 768
Desktop is 1024 x 768 @ 0 Hz
InitializeOrResetSwapChain 1024x768 hdr=0 samples=1
Error getting system window info: Invalid window
Unsupported windowing backend 0

UnloadTime: 0.579083 ms
!!! Another instance of simulator is already using this data folder: /home/ubuntu/.config/unity3d/LGElectronics/SVLSimulator

found manifest at Controllables/controllable_ChargingStation/manifest.json

Fallback handler could not load library /home/ubuntu/Rajesh/SVL Simulator/svlsimulator-linux64-2021.2/simulator_Data/Mono/data-0x2ed3990.so
found manifest at Controllables/controllable_TrafficCone/manifest.json

Fallback handler could not load library /home/ubuntu/Rajesh/SVL Simulator/svlsimulator-linux64-2021.2/simulator_Data/Mono/data-0x2ed7ac0.so
found manifest at Controllables/controllable_TriggerZone/manifest.json

Fallback handler could not load library /home/ubuntu/Rajesh/SVL Simulator/svlsimulator-linux64-2021.2/simulator_Data/Mono/data-0x2800bb0.so
found manifest at NPCs/Bicycles/npc_Bicyclist/manifest.json

found manifest at NPCs/DefaultNPC/npc_BoxTruck/manifest.json

found manifest at NPCs/DefaultNPC/npc_Hatchback/manifest.json

found manifest at NPCs/DefaultNPC/npc_Jeep/manifest.json

found manifest at NPCs/DefaultNPC/npc_SUV/manifest.json

found manifest at NPCs/DefaultNPC/npc_SchoolBus/manifest.json

found manifest at NPCs/DefaultNPC/npc_Sedan/manifest.json

found manifest at Pedestrians/Animals/pedestrian_Deer/manifest.json

found manifest at Pedestrians/Animals/pedestrian_Turkey/manifest.json

found manifest at Pedestrians/Scooters/pedestrian_SegwayKickScooterMaxG30LP/manifest.json

found manifest at Pedestrians/Walkers/pedestrian_Bob/manifest.json

found manifest at Pedestrians/Walkers/pedestrian_EntrepreneurFemale/manifest.json

found manifest at Pedestrians/Walkers/pedestrian_Howard/manifest.json

found manifest at Pedestrians/Walkers/pedestrian_Johny/manifest.json

found manifest at Pedestrians/Walkers/pedestrian_Pamela/manifest.json

found manifest at Pedestrians/Walkers/pedestrian_Presley/manifest.json

found manifest at Pedestrians/Walkers/pedestrian_Robin/manifest.json

found manifest at Pedestrians/Walkers/pedestrian_Stephen/manifest.json

found manifest at Pedestrians/Walkers/pedestrian_Zoe/manifest.json

Loaded NPCs behaviours: 3  NPC models: 7  Pedestrians: 12 Controllables: 3 Bridges: 0in 00:00:00.8520795

Current Database Version: 8

Final Database Version: 8

Caught fatal signal - signo:11 code:1 errno:0 addr:0x50
Obtained 10 stack frames.
#0  0x007fb723473980 in funlockfile
#1  0x007fb724b57ee7 in PhysicsManager::GetDefaultPhysicsSceneHandle() const
#2  0x007fb724a94ceb in UnityScene::~UnityScene()
#3  0x007fb724a91cac in RuntimeSceneManager::~RuntimeSceneManager()
#4  0x007fb724a91525 in StaticDestroyRuntimeSceneManager(void*)
#5  0x007fb7247d6fff in RegisterRuntimeInitializeAndCleanup::ExecuteCleanup()
#6  0x007fb724a7695a in RuntimeCleanup()
#7  0x007fb724c521f6 in PlayerMain(int, char**)
#8  0x007fb723091bf7 in __libc_start_main
#9  0x00000000201029 in _start

**Comment by lemketron** [comment]
> Another instance of simulator is already using this data folder: /home/ubuntu/.config/unity3d/LGElectronics/SVLSimulator

Are you running more than one Simulator instance?

**Comment by rajeshjoshi8792** [comment]
No..i tried to open simulator. But its not opening. So i again tried to open. But getting same issue. I got log in player.log file that simulator connecting to wise.svlsimulator.com. but im unable to see simulator in desktop.

**Comment by lukekenworthy** [comment]
@rajeshjoshi8792 Did you ever find out how to solve this?
