### ISSUE TITLE
error when adding a python api to a vehicle with its own sensor configuration

### ISSUE THREAD

**Issue by gizem-buss** [lgsvl/simulator#1869]
Hello ,
I'm getting an error when adding a python api to a vehicle with its own sensor configuration. Can you help me?

(svl) C:\Users\GizemY\Desktop\simgiz\PythonAPI>C:/Users/GizemY/anaconda3/envs/svl/python.exe c:/Users/GizemY/Desktop/simgiz/PythonAPI/quickstart/autodrive_test.py
Traceback (most recent call last):
  File "c:/Users/GizemY/Desktop/simgiz/PythonAPI/quickstart/autodrive_test.py", line 122, in <module>  
    simScenerio.prepare_sim()
  File "c:/Users/GizemY/Desktop/simgiz/PythonAPI/quickstart/autodrive_test.py", line 25, in prepare_sim
    self.load_vehicle()
  File "c:/Users/GizemY/Desktop/simgiz/PythonAPI/quickstart/autodrive_test.py", line 39, in load_vehicle
    ego = sim.add_agent(env.str("LGSVL__VEHICLE_0", VEHICLE), lgsvl.AgentType.EGO, state)
  File "C:\Users\GizemY\AppData\Roaming\Python\Python36\site-packages\lgsvl\utils.py", line 23, in new_f
    return f(*args, **kwargs)
  File "C:\Users\GizemY\AppData\Roaming\Python\Python36\site-packages\lgsvl\simulator.py", line 162, in add_agent
    uid = self.remote.command("simulator/add_agent", args)
  File "C:\Users\GizemY\AppData\Roaming\Python\Python36\site-packages\lgsvl\remote.py", line 69, in command
    raise Exception(data["error"])
Exception: Object reference not set to an instance of an object

**Comment by gizem-buss** [comment]
In addition, we added our own developed ros module and our own sensors to the vehicle configuration.

**Comment by EricBoiseLGSVL** [comment]
What is prepare_sim()?  Is this your code?  It seems you have an error in that method.
Please provide more information so we can help solve your issue.  Can you show the method?

**Comment by gizem-buss** [comment]
Hello,
prepare_sim() calls 2 more methods. While one is loading the map, the other is creating the ego car. I am trying to create a scenario with random traffic and random pedestrians. 


![image](https://user-images.githubusercontent.com/71923140/141766898-a156dee3-ed69-471f-b04e-80dd15884a61.png)

**Comment by EricBoiseLGSVL** [comment]
I seems like a sensor didn't build right and is failing to load.  Do you have a custom sensor you are using?  I would rebuild and make sure the sensors are built correctly.
I would also check the custom bridge.
- Try running this with a simple config and work your way through the sensors to find the issue.  Be sure to clear cache before running.
- Then test the custom bridge.

**Comment by gizem-buss** [comment]
Hello, 
Yes, I am using custom ros and custom sensors. I think I have built the custom sensors correctly. Because I can use the same sensors without python api. Do I need to do anything special for the python api when creating a new sensor?

**Comment by EricBoiseLGSVL** [comment]
It seems the error comes from a command. Did you create custom api commands in simulator?

**Comment by gizem-buss** [comment]
I guess I didn't create custom api commands in simulator. What does custom api commands mean? I could not fully understand. I am getting the error while adding ego vehicle in api. I am attaching the ego vehicle information. I also get an error without adding the sensors I created to the ego vehicle. I also get it when I create an ego vehicle with my own created ros.

**Comment by EricBoiseLGSVL** [comment]
So you have an issue with the bridge.  What does your custom ros bridge look like?  Did you add to the current Ros bridge or did you make a new one?  Why are you using a custom bridge? What are you trying to do?
![image](https://user-images.githubusercontent.com/45106230/142261600-ccc8d11f-31b9-443d-97e2-8f2853b11feb.png)

- it sounds like the custom bridge has issues.  Did you have errors when you uploaded to the webui?
- Please provide more information on this custom bridge.

**Comment by gizem-buss** [comment]
Hello, I added the existing ros bridge and made changes on it. I added a new sensor and modified it so I could listen to his messages. I did not get any error while building the bridge. With a new simulator I am able to use the custom bridge. But I can't use the same tool with python api.

![image](https://user-images.githubusercontent.com/71923140/142369510-f8415b50-bc95-4132-bd51-ad61a71d4f4c.png)

**Comment by EricBoiseLGSVL** [comment]
With the python api. Are you sure you have a vehicle config set up with the new bridge in the webui?  Do you have the correct config guid?

**Comment by gizem-buss** [comment]
I have a configuration as below.I think it's correct. I can use it in simulator without API.
![image](https://user-images.githubusercontent.com/71923140/142569687-92b001b2-3ff0-436f-a163-5a563a878c69.png)

**Comment by EricBoiseLGSVL** [comment]
With the api are you using that exact config id?
![image](https://user-images.githubusercontent.com/45106230/142697202-fe89a9fc-c248-402c-95b9-6b483b35fbaf.png)
