### ISSUE TITLE
Crashing when running pythonAPI mode

### ISSUE THREAD

**Issue by mozturan** [lgsvl/simulator#2092]
After i succesfully install lgsvl 2020.06 and pythonAPI files, i did `git checkout preview` in PythonAPI. When i try to run `05-ego-drive-in-circle.py` or any code in quickstart file, i get to see that environment and car are setted up but then the simulator immediately close itself. When i end running code i get this:

**Traceback (most recent call last):
  File "05-ego-drive-in-circle.py", line 27, in <module>
    print("Current time = ", sim.current_time)
  File "/home/tinrafiq/.local/lib/python3.8/site-packages/lgsvl/simulator.py", line 69, in current_time
    return self.remote.command("simulator/current_time")
  File "/home/tinrafiq/.local/lib/python3.8/site-packages/lgsvl/remote.py", line 64, in command
    self.cv.wait_for(lambda: self.data is not None)
  File "/usr/lib/python3.8/threading.py", line 337, in wait_for
    self.wait(waittime)
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()**

I don't know what could be wrong, can you help?

**Comment by mozturan** [comment]
i tried to run straight drive code on SingleLaneRoad with API mode. It works slow but at least it works. Could my hardware system be the problem? I have a pretty poor system.
