### ISSUE TITLE
Segmentation fault on Nvidia GTX 1050

### ISSUE THREAD

**Issue by diegoferigo** [lgsvl/simulator#366]
I followed the following steps on my XPS 15 9560 with Ubuntu 18.04:

1. Installed the 2019.09 release of the simulator
1. Started the simulator with `1024x768` and `High` quality (I tried also other combinations) 
1. Created the account though the web ui
1. Downloaded the `BorregasAve` map and the `Jaguar2015XE (No Bridge)` vehicle
1. Started the simulation `BorregasAve, no bridge, data collection`

I got this output in the terminal:

```
/scratch/lgsvlsimulator-linux64-2019.09 took 3m 
❯ ./simulator
Set current directory to /scratch/lgsvlsimulator-linux64-2019.09                                                                                 
Found path: /scratch/lgsvlsimulator-linux64-2019.09/simulator
Mono path[0] = '/scratch/lgsvlsimulator-linux64-2019.09/simulator_Data/Managed'
Mono config path = '/scratch/lgsvlsimulator-linux64-2019.09/simulator_Data/MonoBleedingEdge/etc'
Preloaded 'liblaszip.so'
Preloaded 'libpng.so'
Preloaded 'libsqlite3.so'
Preloaded 'libturbojpeg.so'
Preloaded 'ScreenSelector.so'
Display 0 '0': 1920x1080 (primary device).
Loading player data from /scratch/lgsvlsimulator-linux64-2019.09/simulator_Data/data.unity3d
Logging to /home/dferigo/.config/unity3d/Editor/Player.log
Aborted (core dumped)
```

<details>
 <summary>Player.log</summary>

```
Preloaded type GtkListStore
Preloaded type GtkWindow
Preloaded type GtkVBox
Preloaded type GtkImage
Preloaded type GtkNotebook
Preloaded type GtkHBox
Preloaded type GtkFrame
Preloaded type GtkAlignment
Preloaded type GtkTreeView
Preloaded type GtkLabel
Preloaded type GtkCheckButton
Preloaded type GtkScrolledWindow
Preloaded type GtkComboBox
Desktop is 1920 x 1080 @ 60 Hz
[Vulkan init] extensions: count=17
[Vulkan init] extensions: name=VK_KHR_device_group_creation, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_fence_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_memory_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_semaphore_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_get_display_properties2, enabled=0
[Vulkan init] extensions: name=VK_KHR_get_physical_device_properties2, enabled=0
[Vulkan init] extensions: name=VK_KHR_get_surface_capabilities2, enabled=0
[Vulkan init] extensions: name=VK_KHR_surface, enabled=1
[Vulkan init] extensions: name=VK_KHR_wayland_surface, enabled=1
[Vulkan init] extensions: name=VK_KHR_xcb_surface, enabled=0
[Vulkan init] extensions: name=VK_KHR_xlib_surface, enabled=1
[Vulkan init] extensions: name=VK_KHR_display, enabled=1
[Vulkan init] extensions: name=VK_EXT_direct_mode_display, enabled=0
[Vulkan init] extensions: name=VK_EXT_acquire_xlib_display, enabled=0
[Vulkan init] extensions: name=VK_EXT_display_surface_counter, enabled=0
[Vulkan init] extensions: name=VK_EXT_debug_report, enabled=0
[Vulkan init] extensions: name=VK_EXT_debug_utils, enabled=0
Vulkan detection: 2
Initialize engine version: 2019.1.10f1 (f007ed779b7a)
GfxDevice: creating device client; threaded=1
[Vulkan init] extensions: count=17
[Vulkan init] extensions: name=VK_KHR_device_group_creation, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_fence_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_memory_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_semaphore_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_get_display_properties2, enabled=0
[Vulkan init] extensions: name=VK_KHR_get_physical_device_properties2, enabled=0
[Vulkan init] extensions: name=VK_KHR_get_surface_capabilities2, enabled=0
[Vulkan init] extensions: name=VK_KHR_surface, enabled=1
[Vulkan init] extensions: name=VK_KHR_wayland_surface, enabled=1
[Vulkan init] extensions: name=VK_KHR_xcb_surface, enabled=0
[Vulkan init] extensions: name=VK_KHR_xlib_surface, enabled=1
[Vulkan init] extensions: name=VK_KHR_display, enabled=1
[Vulkan init] extensions: name=VK_EXT_direct_mode_display, enabled=0
[Vulkan init] extensions: name=VK_EXT_acquire_xlib_display, enabled=0
[Vulkan init] extensions: name=VK_EXT_display_surface_counter, enabled=0
[Vulkan init] extensions: name=VK_EXT_debug_report, enabled=0
[Vulkan init] extensions: name=VK_EXT_debug_utils, enabled=0
[Vulkan init] extensions: count=72
[Vulkan init] extensions: name=VK_KHR_8bit_storage, enabled=0
[Vulkan init] extensions: name=VK_KHR_16bit_storage, enabled=0
[Vulkan init] extensions: name=VK_KHR_bind_memory2, enabled=0
[Vulkan init] extensions: name=VK_KHR_create_renderpass2, enabled=0
[Vulkan init] extensions: name=VK_KHR_dedicated_allocation, enabled=1
[Vulkan init] extensions: name=VK_KHR_depth_stencil_resolve, enabled=0
[Vulkan init] extensions: name=VK_KHR_descriptor_update_template, enabled=0
[Vulkan init] extensions: name=VK_KHR_device_group, enabled=0
[Vulkan init] extensions: name=VK_KHR_draw_indirect_count, enabled=0
[Vulkan init] extensions: name=VK_KHR_driver_properties, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_fence, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_fence_fd, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_memory, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_memory_fd, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_semaphore, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_semaphore_fd, enabled=0
[Vulkan init] extensions: name=VK_KHR_get_memory_requirements2, enabled=1
[Vulkan init] extensions: name=VK_KHR_image_format_list, enabled=1
[Vulkan init] extensions: name=VK_KHR_maintenance1, enabled=1
[Vulkan init] extensions: name=VK_KHR_maintenance2, enabled=0
[Vulkan init] extensions: name=VK_KHR_maintenance3, enabled=0
[Vulkan init] extensions: name=VK_KHR_multiview, enabled=0
[Vulkan init] extensions: name=VK_KHR_push_descriptor, enabled=0
[Vulkan init] extensions: name=VK_KHR_relaxed_block_layout, enabled=0
[Vulkan init] extensions: name=VK_KHR_sampler_mirror_clamp_to_edge, enabled=1
[Vulkan init] extensions: name=VK_KHR_sampler_ycbcr_conversion, enabled=0
[Vulkan init] extensions: name=VK_KHR_shader_atomic_int64, enabled=0
[Vulkan init] extensions: name=VK_KHR_shader_draw_parameters, enabled=0
[Vulkan init] extensions: name=VK_KHR_shader_float16_int8, enabled=0
[Vulkan init] extensions: name=VK_KHR_shader_float_controls, enabled=0
[Vulkan init] extensions: name=VK_KHR_storage_buffer_storage_class, enabled=0
[Vulkan init] extensions: name=VK_KHR_swapchain, enabled=1
[Vulkan init] extensions: name=VK_KHR_swapchain_mutable_format, enabled=0
[Vulkan init] extensions: name=VK_KHR_variable_pointers, enabled=0
[Vulkan init] extensions: name=VK_KHR_vulkan_memory_model, enabled=0
[Vulkan init] extensions: name=VK_EXT_blend_operation_advanced, enabled=0
[Vulkan init] extensions: name=VK_EXT_buffer_device_address, enabled=0
[Vulkan init] extensions: name=VK_EXT_conditional_rendering, enabled=0
[Vulkan init] extensions: name=VK_EXT_conservative_rasterization, enabled=0
[Vulkan init] extensions: name=VK_EXT_depth_clip_enable, enabled=0
[Vulkan init] extensions: name=VK_EXT_depth_range_unrestricted, enabled=0
[Vulkan init] extensions: name=VK_EXT_descriptor_indexing, enabled=0
[Vulkan init] extensions: name=VK_EXT_discard_rectangles, enabled=0
[Vulkan init] extensions: name=VK_EXT_display_control, enabled=0
[Vulkan init] extensions: name=VK_EXT_global_priority, enabled=0
[Vulkan init] extensions: name=VK_EXT_host_query_reset, enabled=0
[Vulkan init] extensions: name=VK_EXT_inline_uniform_block, enabled=0
[Vulkan init] extensions: name=VK_EXT_memory_budget, enabled=0
[Vulkan init] extensions: name=VK_EXT_pci_bus_info, enabled=0
[Vulkan init] extensions: name=VK_EXT_post_depth_coverage, enabled=0
[Vulkan init] extensions: name=VK_EXT_sample_locations, enabled=0
[Vulkan init] extensions: name=VK_EXT_sampler_filter_minmax, enabled=0
[Vulkan init] extensions: name=VK_EXT_scalar_block_layout, enabled=0
[Vulkan init] extensions: name=VK_EXT_shader_subgroup_ballot, enabled=0
[Vulkan init] extensions: name=VK_EXT_shader_subgroup_vote, enabled=0
[Vulkan init] extensions: name=VK_EXT_shader_viewport_index_layer, enabled=0
[Vulkan init] extensions: name=VK_EXT_transform_feedback, enabled=0
[Vulkan init] extensions: name=VK_EXT_vertex_attribute_divisor, enabled=0
[Vulkan init] extensions: name=VK_NV_clip_space_w_scaling, enabled=0
[Vulkan init] extensions: name=VK_NV_dedicated_allocation, enabled=0
[Vulkan init] extensions: name=VK_NV_dedicated_allocation_image_aliasing, enabled=0
[Vulkan init] extensions: name=VK_NV_device_diagnostic_checkpoints, enabled=0
[Vulkan init] extensions: name=VK_NV_fill_rectangle, enabled=0
[Vulkan init] extensions: name=VK_NV_fragment_coverage_to_color, enabled=0
[Vulkan init] extensions: name=VK_NV_framebuffer_mixed_samples, enabled=0
[Vulkan init] extensions: name=VK_NV_geometry_shader_passthrough, enabled=0
[Vulkan init] extensions: name=VK_NV_sample_mask_override_coverage, enabled=0
[Vulkan init] extensions: name=VK_NV_shader_subgroup_partitioned, enabled=0
[Vulkan init] extensions: name=VK_NV_viewport_array2, enabled=0
[Vulkan init] extensions: name=VK_NV_viewport_swizzle, enabled=0
[Vulkan init] extensions: name=VK_NVX_device_generated_commands, enabled=0
[Vulkan init] extensions: name=VK_NVX_multiview_per_view_attributes, enabled=0
Vulkan API version 1.1.99
Vulkan vendor=[NVIDIA] id=[10de]
Vulkan renderer=[GeForce GTX 1050] id=[1c8d]
Vulkan device type 2
Vulkan driverversion=[0x6b8a0000] uint=[1804206080]
Vulkan PSO: cache data not found [path=/tmp/LG Silicon Valley Lab/LGSVL Simulator/vulkan_pso_cache.bin]
Begin MonoManager ReloadAssembly
- Completed reload, in  0,073 seconds
WARNING: Shader Unsupported: 'Hidden/Nature/Terrain/Utilities' - All passes removed
ERROR: Shader Shader is not supported on this GPU (none of subshaders/fallbacks are suitable)WARNING: Shader Unsupported: 'Hidden/Nature/Terrain/Utilities' - Setting to default shader.
WARNING: Shader Unsupported: 'HDRP/Lit' - Pass 'IndirectDXR' has no vertex shader
WARNING: Shader Unsupported: 'HDRP/Lit' - Pass 'ForwardDXR' has no vertex shader
WARNING: Shader Unsupported: 'HDRP/Lit' - Pass 'VisibilityDXR' has no vertex shader
WARNING: Shader Unsupported: 'HDRP/Lit' - All passes removed
requesting resize 1024 x 768
resizing window to 1024 x 768
Desktop is 1920 x 1080 @ 60 Hz
InitializeOrResetSwapChain 1024x768 samples=1
WARNING: Shader Unsupported: 'Hidden/PostProcessing/Uber' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/PostProcessing/Uber' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/PostProcessing/FinalPass' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/PostProcessing/FinalPass' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/PostProcessing/FinalPass' - Pass '' has no vertex shader
UnloadTime: 0,571803 ms
WARNING: Shader Unsupported: 'HDRP/Unlit' - Pass 'IndirectDXR' has no vertex shader
WARNING: Shader Unsupported: 'HDRP/Unlit' - Pass 'ForwardDXR' has no vertex shader
WARNING: Shader Unsupported: 'HDRP/Unlit' - Pass 'VisibilityDXR' has no vertex shader
WARNING: Shader Unsupported: 'HDRP/Unlit' - All passes removed
Current Database Version: 1
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Final Database Version: 1
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Setting up 4 worker threads for Enlighten.
  Thread -> id: 7fafbf7fe700 -> priority: 1 
  Thread -> id: 7fafbeffd700 -> priority: 1 
  Thread -> id: 7fafbe7fc700 -> priority: 1 
  Thread -> id: 7fafbdffb700 -> priority: 1 
Cannot create required material because shader is null
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot create required material because shader is null
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

requesting resize 1024 x 768
resizing window to 1024 x 768
Desktop is 1920 x 1080 @ 60 Hz
InitializeOrResetSwapChain 1024x768 samples=1
Compute dispatch: missing UAV ID %d
 
(Filename:  Line: 0)

Compute dispatch: missing texture ID %d
 
(Filename:  Line: 0)

Compute dispatch: missing UAV ID %d
 
(Filename:  Line: 0)

Compute dispatch: missing texture ID %d
 
(Filename:  Line: 0)

Compute dispatch: missing UAV ID %d
 
(Filename:  Line: 0)

Compute dispatch: missing texture ID %d
 
(Filename:  Line: 0)

Compute dispatch: missing texture ID %d
 
(Filename:  Line: 0)

Getting current user
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Listing maps
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Listing cluster
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Listing vehicles
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Listing simulations
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Starting simulation with id 1
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Receiving unhandled NULL exception
#0  0x000000008cab3f in (Unknown)
#1  0x0000000087a85b in (Unknown)
#2  0x0000000083aeaa in (Unknown)
#3  0x0000000083622a in (Unknown)
#4  0x00000000836369 in (Unknown)
#5  0x00000000bf5d00 in (Unknown)
#6  0x007fb0b19d86db in start_thread
#7  0x007fb0b170188f in clone
```

</details>

As reported in https://github.com/lgsvl/simulator/issues/314 I installed all the required vulkan packages. From the log file vulkan seems fine, the problem seems to be somewhere else.

**Comment by martins-mozeiko** [comment]
NULL pointer with call stack like this typically means that Unity tries to use more GPU memory that it is available.

Our BorregasAve and AutomonouStuff maps uses very high detailed textures which uses a lot of memory. It is strongly recommended to run Simulator with GPU that has at least 8GB memory. More if you are using GPU at the same time for other things - running Unity Editor, browser with a lot of content open, fancy desktop compositors, Apollo/Autoware, etc...

Try running SingleLaneRoad or CubeTown maps. If these work, then issue here is running out of GPU memory.

**Comment by diegoferigo** [comment]
@martins-mozeiko Thanks for the feedback. I did some tests and that's exactly what is happening. 

![render1569058470866](https://user-images.githubusercontent.com/469199/65371510-71776080-dc64-11e9-8e92-aa4ed26a197f.gif)

It's unfortunate that so much memory is required, I have a high-end and quite recent XPS 15 laptop and at this point I cannot use it anymore for lgsvl-related activities. Is there any solution to reduce the GPU memory footprint? Choosing a very low-resolution (e.g. 640x480) does not help.

**Comment by diegoferigo** [comment]
Consider that with the 2019.05 version started from a docker container with 1280x720 Ultra, and the following configuration, the GPU memory footprint is just 2250MB. The simulation is quite smooth.

![lgsvl_201905](https://user-images.githubusercontent.com/469199/65371844-21020200-dc68-11e9-9a5a-486967675033.jpeg)

Is the switch to the Web UI such demanding in terms of GPU memory?

**Comment by luqiang21** [comment]
@diegoferigo It is not Web UI needs more GPU memory, it is because the new Unity HDRP and high definition textures.

**Comment by diegoferigo** [comment]
@luqiang21 Is it possible / will it be possible to switch HDRP off?

**Comment by luqiang21** [comment]
@diegoferigo No, the new simulator project is based on HDRP since it provides realistic lighting and high visual fidelity. As @martins-mozeiko said, you can try running SingleLaneRoad or CubeTown maps. And maybe create scenes with low-quality textures but that will decrease the visual fidelity.

**Comment by diegoferigo** [comment]
Thank you @luqiang21 for the feedback. At this point I'll remain with the 2019.05 version while I figure out how to proceed. Closing.
