### ISSUE TITLE
Control LG simulator from ROS node

### ISSUE THREAD

**Issue by alexkutsan** [lgsvl/simulator#628]
Hi
I m trying to subscribe to LG simulator events from ROS node, and control vehicle in simulator from ROS node.
The only information that I found is 
https://www.lgsvlsimulator.com/docs/create-ros2-ad-stack/ 

But I have issues with this tutorial.
 First of all `colcon build  does` not work,
```
student@ro-ptc-48:~/ros2_ws$ colcon build  --symlink-install 
Starting >>> lane_following
Starting >>> message_filters
[0.952s] WARNING:colcon.colcon_ros.task.ament_python.build:Package 'lane_following' doesn't explicitly install a marker in the package index (colcon-ros currently does it implicitly but that fallback will be removed in the future)
[0.953s] WARNING:colcon.colcon_ros.task.ament_python.build:Package 'lane_following' doesn't explicitly install the 'package.xml' file (colcon-ros currently does it implicitly but that fallback will be removed in the future)
--- stderr: lane_following                                                              
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 92, in __call__
    return await task_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_python/build.py", line 105, in build
    return await extension.build(additional_hooks=additional_hooks)
  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 82, in build
    self._symlinks_in_build(args, setup_py_data)
  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 210, in _symlinks_in_build
    .format_map(locals()))
RuntimeError: Provided py_modules 'collect.py' does not exist
---
Failed   <<< lane_following	[ Exited with code 1 ]
--- stderr: message_filters
CMake Error at CMakeLists.txt:14 (find_package):
  By not providing "Findament_cmake_python.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "ament_cmake_python", but CMake did not find one.

  Could not find a package configuration file provided by
  "ament_cmake_python" with any of the following names:

    ament_cmake_pythonConfig.cmake
    ament_cmake_python-config.cmake

  Add the installation prefix of "ament_cmake_python" to CMAKE_PREFIX_PATH or
  set "ament_cmake_python_DIR" to a directory containing one of the above
  files.  If "ament_cmake_python" provides a separate development package or
  SDK, be sure it has been installed.


---
Aborted  <<< message_filters

Summary: 0 packages finished [1.21s]
  1 package failed: lane_following
  1 package aborted: message_filters
  2 packages had stderr output: lane_following message_filters
Provided py_modules 'collect.py' does not exist
```

But I used info from http://wiki.ros.org/catkin/commands/catkin_make instead.

The python script from https://www.lgsvlsimulator.com/docs/create-ros2-ad-stack/  I tried to use subscription script from http://wiki.ros.org/rospy_tutorials/Tutorials/WritingPublisherSubscriber but used `/simulator/sensor/camera/center/compressed` topic.

So that is my script : 

```
import rospy
from std_msgs.msg import String
from std_msgs.msg import String
from sensor_msgs.msg import CompressedImage


def callback(data):
    rospy.loginfo(rospy.get_caller_id() + 'I heard %s', data.data)

def listener():

    # In ROS, nodes are uniquely named. If two nodes with the same
    # name are launched, the previous one is kicked off. The
    # anonymous=True flag means that rospy will choose a unique
    # name for our 'listener' node so that multiple listeners can
    # run simultaneously.
    rospy.init_node('listener', anonymous=True)

    rospy.Subscriber('/simulator/sensor/camera/center/compressed', CompressedImage, callback)

    # spin() simply keeps python from exiting until this node is stopped
    rospy.spin()

if __name__ == '__main__':
    listener()

```

 - I run roscore
 - I run rosbrige `roslaunch rosbridge_server rosbridge_websocket.launch`
 - I run LG simulator `BorregasAve (with Autoware)` map
 - I run my listener ` rosrun beginner_tutorials listener.py ` 

But do not receive any messages. 
And have an errors in rosbridge : 
```
[ERROR] [1581410754.508150]: [Client 0] advertise: Unable to load the manifest for package nmea_msgs. Caused by: nmea_msgs
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/opt/ros/melodic/share
[ERROR] [1581410754.542199]: [Client 0] subscribe: Unable to load the manifest for package autoware_msgs. Caused by: autoware_msgs
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/opt/ros/melodic/share

``` 

Also

**Comment by hadiTab** [comment]
@alexkutsan Not sure why the ros2 build is failing. It says it's missing `collect.py` which is one of the modules provided by the lane_following repo. Maybe it got deleted or moved?

As for the ros1 node you've written. The node looks fine for subscribing to the image, but is that topic actually getting published by the simulator?
You can test it by opening another terminal and listening to the topic:
`rostopic echo /simulator/sensor/camera/center/compressed`

If it is not being published and the bridge is connected, than it's likely an issue in your json config file for the vehicle you are using. See the [docs](https://www.lgsvlsimulator.com/docs/sensor-json-options/) for more information on the json config options.
